name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macos-26
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run build script
        run: ./script/build

  test:
    needs: build
    uses: ./.github/workflows/test.yml
