name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run test script
        run: ./script/test
